### ISSUE TITLE
wee_reports shows syntax warnings

### ISSUE THREAD

**Issue by weswitt** [neoground/neowx-material#30]
on a fresh install of weewx 4.5.1 and neowx-material 1.11 running wee_reports yields the following syntax warnings.  not sure how important this is??

_home_weewx_skins_neowx_material_month__Y__m_html_tmpl.py:406: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month__Y__m_html_tmpl.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month__Y__m_html_tmpl.py:430: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month__Y__m_html_tmpl.py:481: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month__Y__m_html_tmpl.py:493: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month__Y__m_html_tmpl.py:505: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_head_inc.py:172: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_head_inc.py:184: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_header_inc.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_header_inc.py:131: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:150: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:169: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:188: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:207: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:226: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:245: SyntaxWarning: "is" with a literal. Did you mean "=="?
_home_weewx_skins_neowx_material_header_inc.py:263: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_header_inc.py:276: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:152: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:170: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:178: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:201: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:212: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:223: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:234: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:295: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_footer_inc.py:305: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year__Y_html_tmpl.py:412: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year__Y_html_tmpl.py:424: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year__Y_html_tmpl.py:436: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year__Y_html_tmpl.py:487: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year__Y_html_tmpl.py:499: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year__Y_html_tmpl.py:511: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_index_html_tmpl.py:448: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_index_html_tmpl.py:460: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_index_html_tmpl.py:472: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_yesterday_html_tmpl.py:372: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_yesterday_html_tmpl.py:381: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_yesterday_html_tmpl.py:390: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_yesterday_html_tmpl.py:428: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_yesterday_html_tmpl.py:437: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_yesterday_html_tmpl.py:446: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_week_html_tmpl.py:395: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_week_html_tmpl.py:407: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_week_html_tmpl.py:419: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month_html_tmpl.py:395: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month_html_tmpl.py:407: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_month_html_tmpl.py:419: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year_html_tmpl.py:417: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year_html_tmpl.py:429: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year_html_tmpl.py:441: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year_html_tmpl.py:492: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year_html_tmpl.py:504: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_home_weewx_skins_neowx_material_year_html_tmpl.py:516: SyntaxWarning: "is not" with a literal. Did you mean "!="?

**Comment by weswitt** [comment]
and the same warnings are issued when archive records are processed

**Comment by weswitt** [comment]
these warnings are issued when using python 3.8.  i've fixed this on my system, but you may want to change the code to eliminate the warnings

**Comment by LMSSonos** [comment]
@weswitt I have the same issue. Can you tell me how you solved it? I'm using the docker image `felddy/weewx` as base which has python `3.9.1`

**Comment by weswitt** [comment]
I'll try to submit a PR for the fix tomorrow morning

**Comment by iiseppi** [comment]
> I'll try to submit a PR for the fix tomorrow morning

Do you still plan to submit PR for fix? I have same syntax warning in fresh install..

**Comment by crapforge** [comment]
Hello everyone,

this is an older issue which is still existing on my fresh install of WeeWX 4.8.0 using Python 3.9.2.

How can I fix it?

**Comment by MaffooClock** [comment]
And still happening on WeeWX v5.1.0, but the version doesn't matter since the last release of NeoWX Material was over three years ago, and there haven't been anymore commits since then 😳

**Comment by gzin** [comment]
Same thing here (v5.3.1). Has anyone a solution, what to correct in every line and where to find the error exactly?

For example the "yesterday" warnings:

_etc_weewx_skins_neowx_material_yesterday_html_tmpl.py:372: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?
_etc_weewx_skins_neowx_material_yesterday_html_tmpl.py:381: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?
_etc_weewx_skins_neowx_material_yesterday_html_tmpl.py:390: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?
_etc_weewx_skins_neowx_material_yesterday_html_tmpl.py:428: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?
_etc_weewx_skins_neowx_material_yesterday_html_tmpl.py:437: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?
_etc_weewx_skins_neowx_material_yesterday_html_tmpl.py:446: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?

When I look into yesterday.html.tmpl, then I see on line 372:
var raw_data = [

What do I see if I search for "is not" in this file, then I find in line 133:
#if $yesterday.ET.has_data and $yesterday.ET.sum.raw is not None and $yesterday.ET.sum.raw > 0.0
Is it a comment??

Or in line 216:
#if $series2 is not ""
if I change this line to:
#if $series2 != ""
...then the error message from "line 372" is away

Is it the right way to correct?

Regards,
Guenther

**Comment by seehausen** [comment]
I can recommend using the latest fork of this skin
check out
https://github.com/seehase/neowx-material
compatible with weewx 5.2 and a lot of new features and bugfixes

**Comment by seehausen** [comment]
And I can confirm
the latest version from https://github.com/seehase/neowx-material
supports also weewx 5.3.1

see
https://weewx.seehausen.org/

**Comment by gzin** [comment]
Perfect, thank you very much!
Yes, I can confirm too. It works and looks very good. The internationalization (in my case for german) is very complete too.

Best regards from Wels (Upper Austria) to Ingolstadt! :-)

**Comment by seehausen** [comment]
I missed "österreichisch", but that should work in generally
did not test if you create a lang.conf for "de_AT", then I add this to the theme

And I would wonder, if some german translations are missing ;-)

Checkout other features like forecast or MQTT realtime if you like.
You can also share your site too

**Comment by gzin** [comment]
de works well, thanks ;-)

My old site (still productive):
https://www.zinsberger.org/kbwetter/
My new site (still testing):
https://www.zinsberger.org/kbwetter2/

MQTT: is very interesting, since I the old instance also submits to MQTT (for smart home use). Many things in my smart home use MQTT for communication.

For the new site I'm using a Bresser, but I am pushing the data directly into the archive table. Weewx is only generating reports ("weectl report run" every 5 minutes). Perhaps I need a few tasks more.

**Comment by seehausen** [comment]
If you have your data already on a topic, you can just configure the skin to subscribe and do the realtime updates.
you just need to configure

```
    # Use the domain name only, no 'http://' prefix for the host variable
        # host = <your_mqtt_broker_domain_or_ip>
        # port = 9001
        # topic = "weewx/#"
        host =
        port = 9001
        topic = "weewx/#"

        # --- CRITICAL CHANGES ---
        use_ssl = true
        # ------------------------
        websocket_path = /mqtt
        username =
        password =

```
If your mqtt is not public available, it works only in you local LAN but good enough for first tests
